# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /opt/commonapi

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /opt/commonapi

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/commonapi/CMakeFiles /opt/commonapi/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/commonapi/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named E01HelloWorldClient

# Build rule for target.
E01HelloWorldClient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 E01HelloWorldClient
.PHONY : E01HelloWorldClient

# fast build rule for target.
E01HelloWorldClient/fast:
	$(MAKE) -f CMakeFiles/E01HelloWorldClient.dir/build.make CMakeFiles/E01HelloWorldClient.dir/build
.PHONY : E01HelloWorldClient/fast

#=============================================================================
# Target rules for targets named E01HelloWorld-dbus

# Build rule for target.
E01HelloWorld-dbus: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 E01HelloWorld-dbus
.PHONY : E01HelloWorld-dbus

# fast build rule for target.
E01HelloWorld-dbus/fast:
	$(MAKE) -f CMakeFiles/E01HelloWorld-dbus.dir/build.make CMakeFiles/E01HelloWorld-dbus.dir/build
.PHONY : E01HelloWorld-dbus/fast

#=============================================================================
# Target rules for targets named E01HelloWorldService

# Build rule for target.
E01HelloWorldService: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 E01HelloWorldService
.PHONY : E01HelloWorldService

# fast build rule for target.
E01HelloWorldService/fast:
	$(MAKE) -f CMakeFiles/E01HelloWorldService.dir/build.make CMakeFiles/E01HelloWorldService.dir/build
.PHONY : E01HelloWorldService/fast

#=============================================================================
# Target rules for targets named E01HelloWorld-someip

# Build rule for target.
E01HelloWorld-someip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 E01HelloWorld-someip
.PHONY : E01HelloWorld-someip

# fast build rule for target.
E01HelloWorld-someip/fast:
	$(MAKE) -f CMakeFiles/E01HelloWorld-someip.dir/build.make CMakeFiles/E01HelloWorld-someip.dir/build
.PHONY : E01HelloWorld-someip/fast

src-gen/core/v0/commonapi/examples/E01HelloWorldStubDefault.o: src-gen/core/v0/commonapi/examples/E01HelloWorldStubDefault.cpp.o

.PHONY : src-gen/core/v0/commonapi/examples/E01HelloWorldStubDefault.o

# target to build an object file
src-gen/core/v0/commonapi/examples/E01HelloWorldStubDefault.cpp.o:
	$(MAKE) -f CMakeFiles/E01HelloWorldService.dir/build.make CMakeFiles/E01HelloWorldService.dir/src-gen/core/v0/commonapi/examples/E01HelloWorldStubDefault.cpp.o
.PHONY : src-gen/core/v0/commonapi/examples/E01HelloWorldStubDefault.cpp.o

src-gen/core/v0/commonapi/examples/E01HelloWorldStubDefault.i: src-gen/core/v0/commonapi/examples/E01HelloWorldStubDefault.cpp.i

.PHONY : src-gen/core/v0/commonapi/examples/E01HelloWorldStubDefault.i

# target to preprocess a source file
src-gen/core/v0/commonapi/examples/E01HelloWorldStubDefault.cpp.i:
	$(MAKE) -f CMakeFiles/E01HelloWorldService.dir/build.make CMakeFiles/E01HelloWorldService.dir/src-gen/core/v0/commonapi/examples/E01HelloWorldStubDefault.cpp.i
.PHONY : src-gen/core/v0/commonapi/examples/E01HelloWorldStubDefault.cpp.i

src-gen/core/v0/commonapi/examples/E01HelloWorldStubDefault.s: src-gen/core/v0/commonapi/examples/E01HelloWorldStubDefault.cpp.s

.PHONY : src-gen/core/v0/commonapi/examples/E01HelloWorldStubDefault.s

# target to generate assembly for a file
src-gen/core/v0/commonapi/examples/E01HelloWorldStubDefault.cpp.s:
	$(MAKE) -f CMakeFiles/E01HelloWorldService.dir/build.make CMakeFiles/E01HelloWorldService.dir/src-gen/core/v0/commonapi/examples/E01HelloWorldStubDefault.cpp.s
.PHONY : src-gen/core/v0/commonapi/examples/E01HelloWorldStubDefault.cpp.s

src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusDeployment.o: src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusDeployment.cpp.o

.PHONY : src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusDeployment.o

# target to build an object file
src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusDeployment.cpp.o:
	$(MAKE) -f CMakeFiles/E01HelloWorld-dbus.dir/build.make CMakeFiles/E01HelloWorld-dbus.dir/src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusDeployment.cpp.o
.PHONY : src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusDeployment.cpp.o

src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusDeployment.i: src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusDeployment.cpp.i

.PHONY : src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusDeployment.i

# target to preprocess a source file
src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusDeployment.cpp.i:
	$(MAKE) -f CMakeFiles/E01HelloWorld-dbus.dir/build.make CMakeFiles/E01HelloWorld-dbus.dir/src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusDeployment.cpp.i
.PHONY : src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusDeployment.cpp.i

src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusDeployment.s: src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusDeployment.cpp.s

.PHONY : src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusDeployment.s

# target to generate assembly for a file
src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusDeployment.cpp.s:
	$(MAKE) -f CMakeFiles/E01HelloWorld-dbus.dir/build.make CMakeFiles/E01HelloWorld-dbus.dir/src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusDeployment.cpp.s
.PHONY : src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusDeployment.cpp.s

src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusProxy.o: src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusProxy.cpp.o

.PHONY : src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusProxy.o

# target to build an object file
src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusProxy.cpp.o:
	$(MAKE) -f CMakeFiles/E01HelloWorld-dbus.dir/build.make CMakeFiles/E01HelloWorld-dbus.dir/src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusProxy.cpp.o
.PHONY : src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusProxy.cpp.o

src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusProxy.i: src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusProxy.cpp.i

.PHONY : src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusProxy.i

# target to preprocess a source file
src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusProxy.cpp.i:
	$(MAKE) -f CMakeFiles/E01HelloWorld-dbus.dir/build.make CMakeFiles/E01HelloWorld-dbus.dir/src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusProxy.cpp.i
.PHONY : src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusProxy.cpp.i

src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusProxy.s: src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusProxy.cpp.s

.PHONY : src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusProxy.s

# target to generate assembly for a file
src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusProxy.cpp.s:
	$(MAKE) -f CMakeFiles/E01HelloWorld-dbus.dir/build.make CMakeFiles/E01HelloWorld-dbus.dir/src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusProxy.cpp.s
.PHONY : src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusProxy.cpp.s

src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusStubAdapter.o: src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusStubAdapter.cpp.o

.PHONY : src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusStubAdapter.o

# target to build an object file
src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusStubAdapter.cpp.o:
	$(MAKE) -f CMakeFiles/E01HelloWorld-dbus.dir/build.make CMakeFiles/E01HelloWorld-dbus.dir/src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusStubAdapter.cpp.o
.PHONY : src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusStubAdapter.cpp.o

src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusStubAdapter.i: src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusStubAdapter.cpp.i

.PHONY : src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusStubAdapter.i

# target to preprocess a source file
src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusStubAdapter.cpp.i:
	$(MAKE) -f CMakeFiles/E01HelloWorld-dbus.dir/build.make CMakeFiles/E01HelloWorld-dbus.dir/src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusStubAdapter.cpp.i
.PHONY : src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusStubAdapter.cpp.i

src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusStubAdapter.s: src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusStubAdapter.cpp.s

.PHONY : src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusStubAdapter.s

# target to generate assembly for a file
src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusStubAdapter.cpp.s:
	$(MAKE) -f CMakeFiles/E01HelloWorld-dbus.dir/build.make CMakeFiles/E01HelloWorld-dbus.dir/src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusStubAdapter.cpp.s
.PHONY : src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusStubAdapter.cpp.s

src/E01HelloWorldClient.o: src/E01HelloWorldClient.cpp.o

.PHONY : src/E01HelloWorldClient.o

# target to build an object file
src/E01HelloWorldClient.cpp.o:
	$(MAKE) -f CMakeFiles/E01HelloWorldClient.dir/build.make CMakeFiles/E01HelloWorldClient.dir/src/E01HelloWorldClient.cpp.o
.PHONY : src/E01HelloWorldClient.cpp.o

src/E01HelloWorldClient.i: src/E01HelloWorldClient.cpp.i

.PHONY : src/E01HelloWorldClient.i

# target to preprocess a source file
src/E01HelloWorldClient.cpp.i:
	$(MAKE) -f CMakeFiles/E01HelloWorldClient.dir/build.make CMakeFiles/E01HelloWorldClient.dir/src/E01HelloWorldClient.cpp.i
.PHONY : src/E01HelloWorldClient.cpp.i

src/E01HelloWorldClient.s: src/E01HelloWorldClient.cpp.s

.PHONY : src/E01HelloWorldClient.s

# target to generate assembly for a file
src/E01HelloWorldClient.cpp.s:
	$(MAKE) -f CMakeFiles/E01HelloWorldClient.dir/build.make CMakeFiles/E01HelloWorldClient.dir/src/E01HelloWorldClient.cpp.s
.PHONY : src/E01HelloWorldClient.cpp.s

src/E01HelloWorldService.o: src/E01HelloWorldService.cpp.o

.PHONY : src/E01HelloWorldService.o

# target to build an object file
src/E01HelloWorldService.cpp.o:
	$(MAKE) -f CMakeFiles/E01HelloWorldService.dir/build.make CMakeFiles/E01HelloWorldService.dir/src/E01HelloWorldService.cpp.o
.PHONY : src/E01HelloWorldService.cpp.o

src/E01HelloWorldService.i: src/E01HelloWorldService.cpp.i

.PHONY : src/E01HelloWorldService.i

# target to preprocess a source file
src/E01HelloWorldService.cpp.i:
	$(MAKE) -f CMakeFiles/E01HelloWorldService.dir/build.make CMakeFiles/E01HelloWorldService.dir/src/E01HelloWorldService.cpp.i
.PHONY : src/E01HelloWorldService.cpp.i

src/E01HelloWorldService.s: src/E01HelloWorldService.cpp.s

.PHONY : src/E01HelloWorldService.s

# target to generate assembly for a file
src/E01HelloWorldService.cpp.s:
	$(MAKE) -f CMakeFiles/E01HelloWorldService.dir/build.make CMakeFiles/E01HelloWorldService.dir/src/E01HelloWorldService.cpp.s
.PHONY : src/E01HelloWorldService.cpp.s

src/E01HelloWorldStubImpl.o: src/E01HelloWorldStubImpl.cpp.o

.PHONY : src/E01HelloWorldStubImpl.o

# target to build an object file
src/E01HelloWorldStubImpl.cpp.o:
	$(MAKE) -f CMakeFiles/E01HelloWorldService.dir/build.make CMakeFiles/E01HelloWorldService.dir/src/E01HelloWorldStubImpl.cpp.o
.PHONY : src/E01HelloWorldStubImpl.cpp.o

src/E01HelloWorldStubImpl.i: src/E01HelloWorldStubImpl.cpp.i

.PHONY : src/E01HelloWorldStubImpl.i

# target to preprocess a source file
src/E01HelloWorldStubImpl.cpp.i:
	$(MAKE) -f CMakeFiles/E01HelloWorldService.dir/build.make CMakeFiles/E01HelloWorldService.dir/src/E01HelloWorldStubImpl.cpp.i
.PHONY : src/E01HelloWorldStubImpl.cpp.i

src/E01HelloWorldStubImpl.s: src/E01HelloWorldStubImpl.cpp.s

.PHONY : src/E01HelloWorldStubImpl.s

# target to generate assembly for a file
src/E01HelloWorldStubImpl.cpp.s:
	$(MAKE) -f CMakeFiles/E01HelloWorldService.dir/build.make CMakeFiles/E01HelloWorldService.dir/src/E01HelloWorldStubImpl.cpp.s
.PHONY : src/E01HelloWorldStubImpl.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... E01HelloWorldClient"
	@echo "... E01HelloWorld-dbus"
	@echo "... edit_cache"
	@echo "... E01HelloWorldService"
	@echo "... E01HelloWorld-someip"
	@echo "... src-gen/core/v0/commonapi/examples/E01HelloWorldStubDefault.o"
	@echo "... src-gen/core/v0/commonapi/examples/E01HelloWorldStubDefault.i"
	@echo "... src-gen/core/v0/commonapi/examples/E01HelloWorldStubDefault.s"
	@echo "... src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusDeployment.o"
	@echo "... src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusDeployment.i"
	@echo "... src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusDeployment.s"
	@echo "... src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusProxy.o"
	@echo "... src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusProxy.i"
	@echo "... src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusProxy.s"
	@echo "... src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusStubAdapter.o"
	@echo "... src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusStubAdapter.i"
	@echo "... src-gen/dbus/v0/commonapi/examples/E01HelloWorldDBusStubAdapter.s"
	@echo "... src/E01HelloWorldClient.o"
	@echo "... src/E01HelloWorldClient.i"
	@echo "... src/E01HelloWorldClient.s"
	@echo "... src/E01HelloWorldService.o"
	@echo "... src/E01HelloWorldService.i"
	@echo "... src/E01HelloWorldService.s"
	@echo "... src/E01HelloWorldStubImpl.o"
	@echo "... src/E01HelloWorldStubImpl.i"
	@echo "... src/E01HelloWorldStubImpl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

