/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.someip 3.1.12.v201706201046.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/

#ifndef V1_COMMONAPI_EXAMPLES_E03_Methods_SOMEIP_DEPLOYMENT_HPP_
#define V1_COMMONAPI_EXAMPLES_E03_Methods_SOMEIP_DEPLOYMENT_HPP_


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif
#include <CommonAPI/SomeIP/Deployment.hpp>
#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace commonapi {
namespace examples {
namespace E03Methods_ {

// Interface-specific deployment types
typedef CommonAPI::SomeIP::EnumerationDeployment<int32_t> stdErrorTypeEnumDeployment_t;

// Type-specific deployments

// Attribute-specific deployments

// Argument-specific deployment
COMMONAPI_EXPORT extern CommonAPI::SomeIP::StringDeployment foo_x2Deployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::StringDeployment foo_y2Deployment;

// Broadcast-specific deployments

} // namespace E03Methods_
} // namespace examples
} // namespace commonapi
} // namespace v1

#endif // V1_COMMONAPI_EXAMPLES_E03_Methods_SOMEIP_DEPLOYMENT_HPP_
