/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.someip 3.1.12.v201706201046.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <v1/commonapi/examples/E03MethodsSomeIPDeployment.hpp>

namespace v1 {
namespace commonapi {
namespace examples {
namespace E03Methods_ {

// Type-specific deployments

// Attribute-specific deployments

// Argument-specific deployment
CommonAPI::SomeIP::StringDeployment foo_x2Deployment(0, 4, CommonAPI::SomeIP::StringEncoding::UTF16LE);
CommonAPI::SomeIP::StringDeployment foo_y2Deployment(0, 4, CommonAPI::SomeIP::StringEncoding::UTF16LE);

// Broadcast-specific deployments

} // namespace E03Methods_
} // namespace examples
} // namespace commonapi
} // namespace v1
