/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.12.v201705291619.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COMMONAPI_EXAMPLES_E03_METHODS_HPP_
#define V1_COMMONAPI_EXAMPLES_E03_METHODS_HPP_




#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Types.hpp>
#include <cstdint>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace commonapi {
namespace examples {

class E03Methods {
public:
    virtual ~E03Methods() { }

    static inline const char* getInterface();
    static inline CommonAPI::Version getInterfaceVersion();
    
    struct stdErrorTypeEnum : CommonAPI::Enumeration< int32_t> {
        enum Literal : int32_t {
            NO_FAULT = 0,
            MY_FAULT = 1
        };
    
        stdErrorTypeEnum()
            : CommonAPI::Enumeration< int32_t>(static_cast< int32_t>(Literal::NO_FAULT)) {}
        stdErrorTypeEnum(Literal _literal)
            : CommonAPI::Enumeration< int32_t>(static_cast< int32_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< int32_t>(Literal::NO_FAULT):
                case static_cast< int32_t>(Literal::MY_FAULT):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const stdErrorTypeEnum &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const stdErrorTypeEnum &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const stdErrorTypeEnum &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const stdErrorTypeEnum &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const stdErrorTypeEnum &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const stdErrorTypeEnum &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< int32_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< int32_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< int32_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< int32_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< int32_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< int32_t>(_value)); }
    };
};

const char* E03Methods::getInterface() {
    return ("commonapi.examples.E03Methods:v1_2");
}

CommonAPI::Version E03Methods::getInterfaceVersion() {
    return CommonAPI::Version(1, 2);
}


} // namespace examples
} // namespace commonapi
} // namespace v1

namespace CommonAPI {
}


// Compatibility
namespace v1_2 = v1;

#endif // V1_COMMONAPI_EXAMPLES_E03_METHODS_HPP_
