/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.dbus 3.1.12.v201706201043.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <v1/commonapi/examples/E03Methods.hpp>
#include <v1/commonapi/examples/E03MethodsDBusStubAdapter.hpp>

namespace v1 {
namespace commonapi {
namespace examples {

std::shared_ptr<CommonAPI::DBus::DBusStubAdapter> createE03MethodsDBusStubAdapter(
                   const CommonAPI::DBus::DBusAddress &_address,
                   const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection,
                   const std::shared_ptr<CommonAPI::StubBase> &_stub) {
    return std::make_shared< E03MethodsDBusStubAdapter<::v1::commonapi::examples::E03MethodsStub>>(_address, _connection, std::dynamic_pointer_cast<::v1::commonapi::examples::E03MethodsStub>(_stub));
}

void initializeE03MethodsDBusStubAdapter() {
    CommonAPI::DBus::Factory::get()->registerStubAdapterCreateMethod(
        E03Methods::getInterface(), &createE03MethodsDBusStubAdapter);
}

INITIALIZER(registerE03MethodsDBusStubAdapter) {
    CommonAPI::DBus::Factory::get()->registerInterface(initializeE03MethodsDBusStubAdapter);
}

} // namespace examples
} // namespace commonapi
} // namespace v1
