/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.dbus 3.1.12.v201706201043.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COMMONAPI_EXAMPLES_E03_Methods_DBUS_STUB_ADAPTER_HPP_
#define V1_COMMONAPI_EXAMPLES_E03_Methods_DBUS_STUB_ADAPTER_HPP_

#include <v1/commonapi/examples/E03MethodsStub.hpp>
#include "v1/commonapi/examples/E03MethodsDBusDeployment.hpp"

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/DBus/DBusAddressTranslator.hpp>
#include <CommonAPI/DBus/DBusFactory.hpp>
#include <CommonAPI/DBus/DBusStubAdapterHelper.hpp>
#include <CommonAPI/DBus/DBusStubAdapter.hpp>
#include <CommonAPI/DBus/DBusDeployment.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace commonapi {
namespace examples {

template <typename _Stub = ::v1::commonapi::examples::E03MethodsStub, typename... _Stubs>
class E03MethodsDBusStubAdapterInternal
    : public virtual E03MethodsStubAdapter,
      public CommonAPI::DBus::DBusStubAdapterHelper< _Stub, _Stubs...>
     {
public:
    typedef CommonAPI::DBus::DBusStubAdapterHelper< _Stub, _Stubs...> E03MethodsDBusStubAdapterHelper;

    ~E03MethodsDBusStubAdapterInternal() {
        deactivateManagedInstances();
        E03MethodsDBusStubAdapterHelper::deinit();
    }

    virtual bool hasFreedesktopProperties() {
        return false;
    }

    inline static const char* getInterface() {
        return E03Methods::getInterface();
    }

    void fireMyStatusEvent(const int32_t& myCurrentValue);

    void deactivateManagedInstances() {
    }

    static CommonAPI::DBus::DBusGetAttributeStubDispatcher<
        ::v1::commonapi::examples::E03MethodsStub,
        CommonAPI::Version
        > getE03MethodsInterfaceVersionStubDispatcher;

    
    static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
        ::v1::commonapi::examples::E03MethodsStub,
        std::tuple< int32_t, std::string>,
        std::tuple< E03Methods::stdErrorTypeEnum, int32_t, std::string>,
        std::tuple< CommonAPI::DBus::IntegerDeployment, CommonAPI::DBus::StringDeployment>,
        std::tuple< CommonAPI::EmptyDeployment, CommonAPI::DBus::IntegerDeployment, CommonAPI::DBus::StringDeployment>
    
        > fooStubDispatcher;


    E03MethodsDBusStubAdapterInternal(
        const CommonAPI::DBus::DBusAddress &_address,
        const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection,
        const std::shared_ptr<_Stub> &_stub)
    : CommonAPI::DBus::DBusStubAdapter(_address, _connection,false),
      E03MethodsDBusStubAdapterHelper(_address, _connection, false, _stub) {
        E03MethodsDBusStubAdapterHelper::addStubDispatcher({ "foo", "is" }, &fooStubDispatcher);
        E03MethodsDBusStubAdapterHelper::addStubDispatcher({ "getInterfaceVersion", "" }, &getE03MethodsInterfaceVersionStubDispatcher);
    }

protected:
    virtual const char* getMethodsDBusIntrospectionXmlData() const {
        static const std::string introspectionData =
            "<method name=\"getInterfaceVersion\">\n"
                "<arg name=\"value\" type=\"uu\" direction=\"out\" />"
            "</method>\n"
            "<signal name=\"myStatus\">\n"
            "<arg name=\"myCurrentValue\" type=\"i\" />\n"
            "</signal>\n"
            "<method name=\"foo\">\n"
            "<arg name=\"_x1\" type=\"i\" direction=\"in\" />\n"
            "<arg name=\"_x2\" type=\"s\" direction=\"in\" />\n"
            "<arg name=\"_error\" type=\"i\" direction=\"out\" />\n"
            "<arg name=\"_y1\" type=\"i\" direction=\"out\" />\n"
            "<arg name=\"_y2\" type=\"s\" direction=\"out\" />\n"
            "</method>\n"
            ;
        return introspectionData.c_str();
    }

private:
};


template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusGetAttributeStubDispatcher<
    ::v1::commonapi::examples::E03MethodsStub,
    CommonAPI::Version
    > E03MethodsDBusStubAdapterInternal<_Stub, _Stubs...>::getE03MethodsInterfaceVersionStubDispatcher(&E03MethodsStub::getInterfaceVersion, "uu");


template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    ::v1::commonapi::examples::E03MethodsStub,
    std::tuple< int32_t, std::string>,
    std::tuple< E03Methods::stdErrorTypeEnum, int32_t, std::string>,
    std::tuple< CommonAPI::DBus::IntegerDeployment, CommonAPI::DBus::StringDeployment>,
    std::tuple< CommonAPI::EmptyDeployment, CommonAPI::DBus::IntegerDeployment, CommonAPI::DBus::StringDeployment>

    > E03MethodsDBusStubAdapterInternal<_Stub, _Stubs...>::fooStubDispatcher(
    &E03MethodsStub::foo, "iis",
    std::make_tuple(static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr), static_cast< CommonAPI::DBus::StringDeployment* >(nullptr)),
    std::make_tuple(static_cast< CommonAPI::EmptyDeployment * >(nullptr), static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr), static_cast< CommonAPI::DBus::StringDeployment* >(nullptr)));

template <typename _Stub, typename... _Stubs>
void E03MethodsDBusStubAdapterInternal<_Stub, _Stubs...>::fireMyStatusEvent(const int32_t& myCurrentValue) {
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<
    CommonAPI::Deployable< int32_t, CommonAPI::DBus::IntegerDeployment>
    >>::sendSignal(
            *this,
            "myStatus",
            "i",
    CommonAPI::Deployable< int32_t, CommonAPI::DBus::IntegerDeployment>(myCurrentValue, static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr))
    );
}


template <typename _Stub = ::v1::commonapi::examples::E03MethodsStub, typename... _Stubs>
class E03MethodsDBusStubAdapter
    : public E03MethodsDBusStubAdapterInternal<_Stub, _Stubs...>,
      public std::enable_shared_from_this< E03MethodsDBusStubAdapter<_Stub, _Stubs...>> {
public:
    E03MethodsDBusStubAdapter(
        const CommonAPI::DBus::DBusAddress &_address,
        const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection,
        const std::shared_ptr<_Stub> &_stub)
        : CommonAPI::DBus::DBusStubAdapter(
            _address,
            _connection,
            false),
          E03MethodsDBusStubAdapterInternal<_Stub, _Stubs...>(
            _address,
            _connection,
            _stub) {
    }
};

} // namespace examples
} // namespace commonapi
} // namespace v1

#endif // V1_COMMONAPI_EXAMPLES_E03_Methods_DBUS_STUB_ADAPTER_HPP_
